### ISSUE TITLE
Modified Example DB

### ISSUE THREAD

**Issue by AxelKohlepp** [miyako/4d-plugin-notes#1]
I modified "Form1" and the "Form Method" -> better display of Notes Text.

Best regards 

Axel Kohlepp

[Notes.4DB.zip](https://github.com/miyako/4d-plugin-notes/files/1285156/Notes.4DB.zip)

**Comment by miyako** [comment]
Thanks, I've replace the demo 4DB with yours. 
On a separate note, the command to add notes now accepts picture array instead of blob array (and the file name array is ignored). I might bring back "blob array" in the future, but as of now v15 (compiled) can't receive a blob array (perhaps it thinks it is an integer).
